collections:
  Lost Treasures:
    plex_search:
      any:
        title: "Lost Treasures"

  Starkid:
    plex_search:
      any:
        studio:
          - Starkid Productions
          - StarKid
          - Team StarKid
          - Tin Can Brothers
    item_assets: true
    name_mapping: Starkid Productions

  Pro-shots:
    plex_all: true
    filters:
      - actor.count_gte: 1
      - director.count_gte: 1
    summary: Professionally filmed stage recordings and live concert films.

  A Very Potter Musical:
    plex_search:
      all:
        title: "A Very Potter Musical"
    item_assets: true

  Israeli Musicals:
    plex_all: true
    filters:
      - title.regex: '[א-ת]'
      - filepath.regex: '[א-ת]'

  Live:
    plex_search:
      any:
        title:
          - "Sara Bareilles - What's Inside"
          - "Friends of Sondheim Concert"
          - "Gavin Creel"
          - "Adam Pascal, So Far..."
