collections:
  Ghosts:
    plex_search:
      all:
        title: "Ghosts"
        genre: Comedy
    sync_mode: sync

  Pirates:
    plex_search:
      any:
        title:
          - "Black Sails"
          - "Our Flag Means Death"
          - "One Piece"
    sync_mode: sync

  Musical Shows:
    plex_search:
      all:
        genre: Musical
    sync_mode: sync

  # My Lists:
  #   blank_collection: true
  #   collection_mode: hide
  #   sort_title: "!091_!My Lists"
  #   url_poster: https://raw.githubusercontent.com/Kometa-Team/Kometa/nightly/defaults/separators/orig/separator.png

  This is what i'll talk about:
    plex_search:
      any:
        title:
          - "Our Flag Means Death"
          - "Interview with the Vampire"
          - "Heated Rivalry"
    sort_title: "!091_This is what i'll talk about"
    sync_mode: sync
