#!/usr/bin/env python3
"""CLI wrapper for assets organization.

Configures logging and calls PosterOrganizer from `poster_handler.py`.
Future: Can be extended with ThumbnailOrganizer, BackgroundOrganizer, etc.
"""

import argparse
import logging
import os
from pathlib import Path

logger = logging.getLogger(__name__)

# Script directory
SCRIPT_DIR = Path(__file__).resolve().parent

# Load asset helper env if present (generated by scripts/generate_asset_helper_env.sh)
ASSET_ENV = SCRIPT_DIR.parent.parent / ".env"
if ASSET_ENV.exists():
    try:
        from dotenv import load_dotenv

        load_dotenv(ASSET_ENV)
    except ImportError:
        logger.debug("python-dotenv not installed; skipping .env load")

# Environment-driven defaults
DEFAULT_ASSET_TARGET = SCRIPT_DIR.parent.parent / "config" / "assets"
POSTERS_SOURCE_DIR = os.getenv("POSTERS_SOURCE_DIR", "Posters")
ASSET_TARGET_DIR = os.getenv("ASSET_TARGET_DIR", str(DEFAULT_ASSET_TARGET))
ASSET_FORCE_PNG = os.getenv("ASSET_FORCE_PNG", "true").strip().lower() in {
    "1",
    "true",
    "yes",
    "on",
}
ASSET_EXCEPTION_MAPPINGS = os.getenv(
    "ASSET_EXCEPTION_MAPPINGS", "exception_mappings.json"
)

HANDLERS = {"poster_handler"}  # Future: add overlay_handler, etc.


def resolve_path(path_value: str) -> Path:
    """Resolve CLI/env paths with sensible fallbacks.

    Relative paths are first resolved from this script directory, then from the
    project root if needed.
    """
    raw_path = Path(path_value)
    if raw_path.is_absolute():
        return raw_path

    script_resolved = SCRIPT_DIR / raw_path
    if script_resolved.exists():
        return script_resolved

    project_root_resolved = SCRIPT_DIR.parent.parent.parent / raw_path
    return project_root_resolved


def ensure_exception_mapping_file(path: Path, dry_run: bool) -> None:
    """Create an empty exception mapping JSON when missing."""
    if path.exists():
        return

    if dry_run:
        logger.info("DRY-RUN: would create missing exception mappings at %s", path)
        return

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("{}\n", encoding="utf-8")
    logger.info("Created missing exception mappings file at %s", path)


def main() -> int:
    """Main entry point for the CLI."""
    parser = argparse.ArgumentParser(
        description="Organize downloaded posters and assets for Kometa"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be done without making changes",
    )
    parser.add_argument(
        "--source",
        type=str,
        default=POSTERS_SOURCE_DIR,
        help="Source directory containing downloaded assets",
    )
    parser.add_argument(
        "--target",
        type=str,
        default=ASSET_TARGET_DIR,
        help="Target directory for organized assets",
    )
    parser.add_argument(
        "--force-png",
        action=argparse.BooleanOptionalAction,
        default=ASSET_FORCE_PNG,
        help="Convert all images to PNG format",
    )
    parser.add_argument(
        "--exception-mappings",
        type=str,
        default=ASSET_EXCEPTION_MAPPINGS,
        help="Path to exception mappings JSON file",
    )
    parser.add_argument(
        "--init-exception-mappings",
        action="store_true",
        help="Create empty exception mappings JSON if it does not exist",
    )
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

    source = resolve_path(args.source)
    target = resolve_path(args.target)
    exception_mappings = resolve_path(args.exception_mappings)

    if args.init_exception_mappings:
        ensure_exception_mapping_file(exception_mappings, args.dry_run)

    from handlers import Organizer
    from poster_handler import PosterOrganizer

    for handler in HANDLERS:
        logger.info("Using handler: %s", handler)
        if handler == "poster_handler":
            organizer = PosterOrganizer(
                source, target, exception_mappings, args.force_png, dry_run=args.dry_run
            )
        else:
            logger.warning("Unknown handler: %s", handler)
            continue

        for category in Organizer.ASSET_CATEGORIES:
            if not organizer.organize(category):
                logger.error("Failed to organize assets for category: %s", category)
                continue

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
